version: '3'

services:
  philosophy_postgres:
    image: postgres:latest
    container_name: philosophy_postgres
    tty: true
    restart: always
    networks:
      - philosophy_postgres_network
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./:/var/lib/postgresql
      - ./postgres_data:/var/lib/postgresql/data

  philosophy_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: philosophy_pgadmin
    tty: true
    restart: always
    networks:
      - philosophy_postgres_network
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      TZ: "Europe/Moscow"
      PGADMIN_DEFAULT_EMAIL: "dmitriytarasov122@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

networks:
  philosophy_postgres_network:
    driver: bridge
